ballOfSteel:
  lobbyName: "lobby"
  nomberOfPlayerParTeam: 1
  world: "world1"
  time: 1
  range: 100
  coordonee:
    mid:
      x: 0
      y: 50
      z: 0
    start:
      x: 10000
      y: 50
      z: 0
    finish:
      x: 
      y: 
      z: 
  equipe:
    yellow:
      coordonee:
        spawn:
          x: 70
          y: 50
          z: 70
    red:
      coordonee:
        spawn:
          x: -70
          y: 50
          z: 70
    blue:
      coordonee:
        spawn:
          x: -70
          y: 50
          z: -70
    green:
      coordonee:
        spawn:
          x: 70
          y: 50
          z: -70
       